### ISSUE TITLE
ItemSetChange event not fired after adding/removing filters to container

### ISSUE THREAD

**Issue by rste79** [tlaukkan/vaadin-lazyquerycontainer#47]
Hi,
I've attached an ItemSetChangeListener to the container (LazyQueryContainer version 2.0.8) but this event is not fired when a filter is added/removed, even if adding/removing the filter actually changes the item set.
Thanks in advance,
Stefano

**Comment by tuscland** [comment]
Hello @tlaukkan,

How do I enable the behavior your described on Jun 14, 2013?
I have spurious requests when filters are removed.
I just want one request to happen when the user is done selecting options.

The item set change notification behavior is sealed with final or private methods, so there is no way I can extend or modify it.

Best,
Cam

**Comment by tlaukkan** [comment]
Hi @tuscland 

A patch introduces behavior that refreshes container after each filter change which can run multiple unnecessary queries for example when multiple filters are removed. This behavior was introduced in a pull request and I missed the fact when accepting it. It is probably good time to think about adding functionality for mass removing filters in LazyQueryContainer API so that it disabled the filters at that point.

For now you can set query size to 0 before removing filters. If you are using LazyEntityQuery this disables queries. If you have custom query you can implement the same behavior. After removing filters you can reset query size to correct value and refresh your view.

Br,
Tomi

**Comment by tuscland** [comment]
Great, thank you!
