### ISSUE TITLE
Sorting nested properties does not work properly

### ISSUE THREAD

**Issue by gizmo1177** [tlaukkan/vaadin-lazyquerycontainer#51]
Sorting nested properties does not work properly for me. I have a simple OneToOne relation. A person CAN have an account. When I click on the table icon of the account column the data will be sorted. When I scroll down I see the following stacktrace:

SEVERE: java.lang.RuntimeException: Unable to get item id for index: 0 from container using Container.Indexed#getIdByIndex() even though container.size() > endIndex. Returned item id was null. Check your container implementation!
at com.vaadin.data.ContainerHelpers.getItemIdsUsingGetIdByIndex(ContainerHelpers.java:90) 

I think this problem occurs for that persons that have no account assigned.

I initialize the container as following:
<code>
LazyEntityContainer container = new LazyEntityContainer(manager, Person.class, 200, "id", false, true, true);
container.addContainerProperty("firstName", String.class, "", true, true);
container.addContainerProperty("account.loginName", String.class, "", true, true);
</code>

**Comment by kchantzara** [comment]
I am using a Grid with LazyEntityContainer and I need to sort on a nested property that is nullable, just as @gizmo1177 has explained earlier.
I have configured the max nested property depth 
`entityContainer.getQueryView().getQueryDefinition().setMaxNestedPropertyDepth(4);`
and my nested property is as follows
`entityContainer.addContainerProperty("vessel.name", String.class, null, false, true);`
The vessel property is null for some entities.
Inspecting the select statement that is finally executed, I noticed that it makes a Cartesian join between the entity and the nested table,  which eliminates the null values, thus returning less rows that the SELECT COUNT() statement has initially counted.
I see that this issue is closed, but it is not clear to me if this is some functionality that is not supported by LazyEntityContainer by decision, or I am missing something in my code.
In case the ORM implementation makes some difference, I am using EclipseLink 2.6.2.
